#
# Makefile for the Loongson 2F-based hardware
#

# common code for all Loongson 2F-based systems
obj-$(CONFIG_STLS2F_SYSTEMS) += arch/mips/lemote/lm2f/common

# specific configuration for the Gdium Liberty 1000
obj-$(CONFIG_GDIUM_LIBERTY) += arch/mips/lemote/lm2f/gdium

