#
# Makefile for the Loongson 2F-based hardware
#

# common code for all Loongson 2F-based systems
obj-$(CONFIG_STLS2F_SYSTEMS) += common/

# specific configuration for the Gdium Liberty 1000
obj-$(CONFIG_EMTEC_GDIUM) += gdium/

