install:
	cp preferences.fdi /etc/hal/fdi/policy
	cp hal-system-lcd-get-brightness-linux /usr/lib/hal/scripts/linux
	cp hal-system-lcd-set-brightness-linux /usr/lib/hal/scripts/linux
	/etc/init.d/hal restart
