# Makefile for RT specific drivers

obj-$(CONFIG_BACKFIRE) += backfire.o
obj-$(CONFIG_SCHED_CLOCK_LAT) += sched_clock_latency.o
obj-$(CONFIG_INTR_LAT) += interrupt_latency.o
obj-$(CONFIG_BLOCKSYS) += blocksys.o
