snd-soc-sm501-objs := sm501-pcm.o
snd-soc-sm501-ac97-objs := sm501-ac97.o sm501-u8051.o
snd-soc-sm501-ac97-dev-objs := sm501-ac97-dev.o

obj-$(CONFIG_SND_SM501_SOC) += snd-soc-sm501.o
obj-$(CONFIG_SND_SM501_SOC_AC97) += snd-soc-sm501-ac97.o
obj-$(CONFIG_SND_SM501_SOC_AC97_DEVICE) += snd-soc-sm501-ac97-dev.o
